# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env: 
      platform: gcp
      region: us-east-1
      account: 12345

      username: ${{secrets.USERNAME}}
      password: ${{secrets.PASSWORD}}

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Muestrame el mensaje"
        run: echo "hola mundo"
      
      - name: "Mostrando valores de entorno"
        if: ${{env.platform == 'gcp' }}
        run: |
          echo "esto es el valor de platform: ${{env.platform}}"
          echo "esto es el valor de region: ${{env.region}}"
          echo "esto es el valor de account: ${{env.account}}"

          echo "esto es el valor de username: ${{env.username}}"
          echo "esto es el valor de password: ${{env.password}}"

      - name: "Mostrando valores solo si el usuario es el correcto"
        if: ${{env.username == github.actor}}
        run: |
          echo "usuario correcto"


      - name: "Mostrando variables por defecto de github"
        run: |
          echo "Evento: ${{toJSON(github.event)}}"
          echo "github_ACTOR: ${{github.actor}}"
          echo "github_ACTOR: $GITHUB_ACTOR"

